title: "Tan 的经验笔记"
description: "短小、可复用的科研与教学经验"
url: "https://tan-qiao-guo.github.io"
baseurl: "/blogs"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-paginate

paginate: 10
paginate_path: /page:num/

search: true
search_full_content: false

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      toc: false
